import type { Metadata } from "next";
import { Jost, Josefin_Sans } from "next/font/google";
import { AppRootLayout } from "@/components/layout/app-root-layout";
import "@/styles/globals.css";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${josefinSans.variable}`}>
        <AppRootLayout>{children}</AppRootLayout>
      </body>
    </html>
  );
}
