import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AppRootLayout } from "@/components/app-root-layout";

import "@/styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Commerce - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <AppRootLayout>
          {children}
        </AppRootLayout>
      </body>
    </html>
  );
}
