import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AdminDashboardLayout } from "@/components/dashboard/dashboard-layout";
import { AppProvider } from "@/providers/app-provider";
import { LayoutProvider } from "@/providers/layout-provider";

import "@/styles/globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable}`}>
                <AppProvider>
                    <LayoutProvider>
                        <AdminDashboardLayout>
                            {children}
                        </AdminDashboardLayout>
                    </LayoutProvider>
                </AppProvider>
            </body>
        </html>
    );
}
