import { Inter } from "next/font/google";

import { UserDashboardLayout } from "@/components/user-dashboard/user-dashboard-layout";
import { AppProvider } from "@/providers/app-provider";

import type { Metadata } from "next";
import "@/styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AccountLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <AppProvider>
          <UserDashboardLayout>{children}</UserDashboardLayout>
        </AppProvider>
      </body>
    </html>
  );
}
