export const cartData = [
  {
    id: 1,
    image: "/assets/images/cart/hatil-sofa-anderson-279.svg",
    name: "HATIL Sofa Anderson-279",
    model: "OC-100",
    quantity: 2,
    price: 120,
  },
  {
    id: 2,
    image: "/assets/images/cart/l23-club-cabriole-sofa.svg",
    name: "L23 Club Cabriole Sofa",
    model: "WD-200",
    quantity: 1,
    price: 250,
  },
  {
    id: 3,
    image: "/assets/images/cart/m23-mid-century-modern-sofa.svg",
    name: "Wireless Mouse",
    model: "WM-300",
    quantity: 3,
    price: 25,
  },
  {
    id: 4,
    image: "/assets/images/cart/l23-club-cabriole-sofa.svg",
    name: "L23 Club Cabriole Sofa",
    model: "MK-400",
    quantity: 1,
    price: 80,
  },
  {
    id: 5,
    image: "/assets/images/cart/hatil-sofa-anderson-279.svg",
    name: "HATIL Sofa Anderson-279",
    model: "DL-500",
    quantity: 2,
    price: 45,
  },
  {
    id: 6,
    image: "/assets/images/cart/house-hold-almirah-carnelian.svg",
    name: "Bookshelf Organizer",
    model: "BO-600",
    quantity: 1,
    price: 150,
  },
  {
    id: 7,
    image: "/assets/images/cart/l23-club-cabriole-sofa.svg",
    name: "L23 Club Cabriole Sofa",
    model: "GH-700",
    quantity: 1,
    price: 90,
  },
  {
    id: 8,
    image: "/assets/images/cart/l23-club-cabriole-sofa.svg",
    name: "Laptop Stand",
    model: "LS-800",
    quantity: 2,
    price: 60,
  },
  {
    id: 9,
    image: "/assets/images/cart/m23-mid-century-modern-sofa.svg",
    name: "Portable Hard Drive",
    model: "HD-900",
    quantity: 1,
    price: 110,
  },
  {
    id: 10,
    image: "/assets/images/cart/house-hold-almirah-carnelian.svg",
    name: "Smartphone Holder",
    model: "SH-1000",
    quantity: 4,
    price: 20,
  },
];
