export const TAGS = {
  attributes: "attributes",
  addresses: "addresses",
  address: "address",
  attributes: "attributes",
  products: "products",
  product: "product",
  brands: "brands",
  campaign: "campaign",
  cart: "cart",
  campaigns: "campaigns",
  categories: "categories",
  coupons: "coupons",
  coupon: "coupon",
  files: "files",
  orders: "orders",
  reviews: "reviews",
  users: "users",
};
