export const TAGS = {
    products: 'products',
    product: 'product',
    brands: 'brands',
    campaign: 'campaign',
    campaigns: 'campaigns',
    categories: "categories",
    coupons: "coupons",
    coupon: "coupon",
    files: "files",
    cart: "cart",
    reviews: "reviews",
    orders: "orders",
    users: "users",
}