import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AppProvider } from "@/providers/app-provider";
import { LayoutProvider } from "@/providers/layout-provider";

import "@/styles/globals.css";
import { AdminDashboardLayout } from "./_components/dashboard-layout";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Commerce - Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <AppProvider>
          <LayoutProvider>
            <AdminDashboardLayout>{children}</AdminDashboardLayout>
          </LayoutProvider>
        </AppProvider>
      </body>
    </html>
  );
}
