export const CONFIG = {
  node_env: process.env.NODE_ENV,
  salt_rounds: process.env.SALT_ROUNDS,
  jwt_access_secret: process.env.JWT_ACCESS_SECRET,
  jwt_access_expiresIn: process.env.JWT_ACCESS_EXPIRESIN,
  jwt_refresh_secret: process.env.JWT_REFRESH_SECRET,
  jwt_refresh_expiresIn: process.env.JWT_REFRESH_EXPIRESIN,
  supabase_bucket_url: process.env.SUPABASE_BUCKET_URL,
  supabase_service_role_key: process.env.SUPABASE_SERVICE_ROLE_KEY,
  user_bucket: process.env.USER_BUCKET,
  general_bucket: process.env.GENERAL_BUCKET,
  direct_db_url: process.env.DIRECT_DB_URL,
  tax: Number(process.env.TAX) || 5,
  app_name: process.env.APP_NAME,
  app_email_address: process.env.APP_EMAIL_ADDRESS,
  email_app_pass: process.env.EMAIL_APP_PASS,
};
